# Generated by Django 5.0.2 on 2024-03-08 12:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Hotel_Name', models.CharField(max_length=255)),
                ('Room_Category', models.CharField(choices=[('single', 'single'), ('double', 'double'), ('suite', 'suite'), ('dormetory', 'dormetory')], max_length=255)),
                ('Address', models.CharField(max_length=255)),
                ('Destination_Near', models.CharField(blank=True, max_length=255, null=True)),
                ('Aminities', models.CharField(max_length=255)),
                ('Price', models.FloatField()),
                ('description', models.CharField(max_length=1000)),
                ('Hotel_pic', models.FileField(upload_to='HOTel_pic')),
                ('availability', models.BooleanField(default=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HotelBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booker_Name', models.CharField(max_length=255)),
                ('booker_phone', models.CharField(max_length=255)),
                ('booker_address', models.CharField(max_length=255)),
                ('booking_date', models.DateField()),
                ('date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('Hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.hotels')),
            ],
        ),
    ]
